backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  # These lines should *not* be indented
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: Experiences
    name: experiences
    format: json
    folder: content/experiences
    create: true
    fields:

      - label: Year
        name: title
        widget: string

      - label: Jobs
        name: jobs
        widget: list
        fields:

        - label: Company
          name: company
          widget: string

        - label: Description
          name: description
          widget: string

        - label: Position
          name: position
          widget: string

        - label: Start Date
          name: start_date
          widget: string

        - label: End Date
          name: end_date
          widget: string

        - label: Contributions
          name: contributions
          widget: list
          fields:

          - label: Header
            name: header
            widget: string

          - label: Subheader
            name: subheader
            widget: string

          - label: Examples
            name: examples
            widget: list
            field: {label: Example, name: example, widget: string}

  - label: Skills
    name: skills
    format: json
    folder: content/skills
    create: true
    fields:

      - label: Categories
        name: title
        widget: string

      - label: Skills
        name: skills
        widget: list
        fields:

          - label: Skill
            name: skill
            widget: string

          - label: Capabilities
            name: capabilities
            widget: list
            field: {label: Capability, name: capability, widget: string}

